### ISSUE TITLE
Add /lunch command to get lunch data

### ISSUE THREAD

**Issue by dmitler** [eugenzyx/pbc-bot#2]

**Comment by eugenzyx** [comment]
What I expect to see as a functions set of this command?

1. Ability to get your order using `/lunch <name>` syntax.
2. Ability to have a daily automatic reminder at ~2.00 pm with the same information you could get using the command from the first item.
3. (?) Have daily reminder to order a lunch if you haven't done so yet. (Not exactly a bot command, but let's think about if we still want this feature to be present.)

**Comment by eugenzyx** [comment]
Actually, the second item isn't a bot command either.

**Comment by eugenzyx** [comment]
Let's currently stick to the first item only.
