### ISSUE TITLE
/lunch ehancements

### ISSUE THREAD

**Issue by eugenzyx** [eugenzyx/pbc-bot#23]
Currently, the `/lunch` command prints the name of a user as it was passed to the command (as a parameter). It should rather write the matched name of a person.

In other words, if you say this:

`/lunch Sabina`

the output is something like this:

`Sabina ordered Суп гречаний з фрикадельками, котлета печінкова з цибулею + картопляне пюре, гриби по-корейськи from FEST`

instead I'd be better to know Sabina's last name:

`Sabina Schneider ordered Суп гречаний з фрикадельками…`

**Comment by deril** [comment]
Due to @eugenzyx explanation, in case of entering only first name, command should output all guys with this name and also their surnames

**Comment by eugenzyx** [comment]
c4f5c54afefde8edfa48c1482cbc5582f63975ea
